version: "3.7"
services:
  db:
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tlc
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  back:
    build: ./api
    restart: on-failure
    ports:
      - "8080:8080"
#    deploy:
#      replicas: 6
#      placement:
#        max_replicas_per_node: 1
#      restart_policy:
#        condition: on-failure
  server:
    image: bunkerity/bunkerized-nginx
    volumes:
      - ./server-confs:/server-confs
      - ./front/dist/tlcfront:/www
      - ./config:/config
    ports:
      - "80:8080"
      - "443:83"
    environment:
      - SERVER_NAME=tlap.diverse-team.fr
    links:
      - db
      - etherpad
      - mail
