
db:
  image: mysql:8.0.22
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=tlc
    - MYSQL_ROOT_DATABASE=tlc
    - MYSQL_ROOT_USER=tlc
    - MYSQL_PASSWORD=tlc
etherpad:
  image: etherpad/etherpad:stable
  ports:
    - "9001:9001"
  volumes:
    - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
mail:
  image: bytemark/smtp
  restart: always
  ports:
    - "2525:25"

